### PR TITLE
Add prefix support to hattrie

### PR DESCRIPTION
**Pull request by cjgibson**

### CODE REVIEW

**Comment by cjgibson** [comment]
Attempted to merge the prefix iteration logic from https://github.com/luikore/hat-trie, as suggested in #20, and add associated unittests. Very much stumbled my way through learning how the library works, so please let me know if there are any modifications or improvements I can make to the above.

**Comment by cjgibson** [comment]
Bump - @dcjones

**Comment by dcjones** [comment]
Looks good @cjgibson, thanks for the effort!

**Comment by cjgibson** [comment]
Thanks for the merge @dcjones - quick question for my sanity:

We use `hattrie_find` to locate the initial node during prefix iteration:
https://github.com/dcjones/hat-trie/blob/master/src/hat-trie.c#L661

Which appears to work _except_ in the case that no bucket within the hat-trie satisfies even a single character of the prefix, and we force the initial node to be the root node:
https://github.com/dcjones/hat-trie/blob/master/src/hat-trie.c#L663

Is this intentional behavior on the part of `hattrie_find`? Or am I missing something obvious here?

**Comment by dcjones** [comment]
It's been a long time since I wrote or really looked at this code, but I think my intention was that if `hattrie_find` finds an appropriate node it returns a valid pointer to it, and if it doesn't it sets the `flag` field in the returned `note_ptr` to `NULL`, and the other fields (the actual pointers) are just ignored.

So I don't think there was an intended behavior when a bucket wasn't found. I guess a better solution then would be to change `hattrie_find` to work whatever way is useful in those cases.

**Comment by cjgibson** [comment]
Okay, thanks for that added detail. That was my initial assumption, but I didn't want to modify the existing behavior JIC someone upstream is somehow reliant on it.

I remember thinking that `hattrie_consume` might be a preferred alternative to `hattrie_find` for my use case; I'll make the change and run some timing tests to see if that ends up being true. Cheers!

**Comment by cjgibson** [comment]
Just a heads, I tested using `hattrie_consume` in lieu of `hattrie_find`, and while use of the former was sufficient to pass my unittests, it resulted in a slower runtime when compared to the latter.

**Pull request merged**
